# arXiv Daily Digest Configuration
# Copyright (c) 2025 Erik Bitzek
# Licensed under GNU AGPL v3

# arXiv search settings
arxiv:
  # Categories to search (can be multiple)
  categories:
    - cond-mat.mtrl-sci
  
  # Time window in hours (168 = last 7 days, 72 = last 3 days, 24 = last day)
  time_window_hours: 168
  
  # Maximum results to retrieve
  max_results: 100

# Keywords with Boolean logic
# Each entry is processed as: (keyword1 AND keyword2) OR (keyword3)
# Use lists for AND logic, separate entries for OR logic
keywords:
  - ["dislocation", "molecular dynamics"]
  - ["dislocation", "atomistic simulation"]
  - ["fracture", "molecular dynamics"]
  - ["fracture", "atomistic simulation"]
  - ["crack", "molecular dynamics"]
  - ["crack", "atomistic simulation"]
  - ["grain boundary", "molecular dynamics"]
  - ["grain boundary", "atomistic simulation"]
  - ["grain boundaries", "molecular dynamics"]
  - ["grain boundaries", "atomistic simulation"]

# OpenAI settings
openai:
  # Model to use for summaries
  model: "gpt-4o-mini"  # Cost-effective for summaries
  
  # Maximum tokens for each summary
  max_tokens: 150
  
  # Temperature (0 = deterministic, 1 = creative)
  temperature: 0.3

# Output settings
output:
  # Format: 'text', 'email', or 'both'
  format: 'both'
  
  # Output file path (for text format)
  output_file: 'daily_digest.txt'
  
  # Include abstract in output (in addition to AI summary)
  include_abstract: false

# Email settings (optional, for Phase 2)
email:
  enabled: true
  # SMTP server settings will be stored as environment variables
  recipient: "e.bitzek@mpie.de"
  subject: "arXiv Daily Digest - {date}"